version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /data/plex/config:/config
      - /mnt/ssd/cartoons:/cartoons
      - /mnt/ssd/movies:/movies
      - /mnt/ssd/tv_series:/tv_series
    restart: unless-stopped

